Add core and shared logic
VolhaAdaska/WhoWantsToBeAMillionaire pull request #1
Opened 2020-11-23 15:47 UTC by VolhaAdaska

2020-11-23 16:09 UTC, oleg-vasilyev commented on src/app/app.component.html
> +          routerLink="/home"
имеет смысл использовать тут переменную, ту же, что в роутинге

2020-11-23 16:10 UTC, oleg-vasilyev commented on src/app/app.component.html
> +        [ngIfElse]="loggedOut"
*ngIf="!isLoggedIn; else loggedOut"

2020-11-23 16:33 UTC, oleg-vasilyev requested changes

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/app.component.html
> +            routerLink="/login"
переменная из роутинга

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/app.component.html
> +            routerLink="/register"
и тут

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/app.component.html
> +            routerLink="/top-users"
и тут

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/app.component.html
> +            routerLink="/game"
и тут

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/app.component.html
> +          routerLink="/home"
и тут

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/app.component.html
> +          (click)="logout()"
имеет смысл помечать все обработчики output с помощью постфикса:
logoutHandler()

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/app.component.ts
> +  styleUrls: ['./app.component.scss'],
стратегия OnPush

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/app.component.ts
> +  get isLoggedIn(): boolean {
public

порядок не соблюдается - сначала геттеры, свойства, потом конструктор, потом публичные методы
это есть в линте, если он не дал тут ошибку - значит он не работает

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/auth-services/auth.service.ts
> +  private _serverUrl = 'http://localhost:3000';
имеет смысл сделать эту штуку readonly

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/auth-services/auth.service.ts
> +        localStorage.setItem(this._CURRENTUSER, JSON.stringify(user));
JSON.stringify(user) -> User.deparse(user)

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/auth-services/auth.service.ts
> +    return localStorage.getItem(this._CURRENTUSER) !== null;
лучше хранить юзера на this
если почистить ls в работающем сайте ты получишь false, хотя мы все еще залогинены

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.html
> +  (ngSubmit)="onSubmit()"
submitHandler()

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.html
> +        formControlName="email"
не рекомендуется юзать formControlName - так как это строка, которая может измениться и ты не увидишь ошибки
лучше сделать переменную в компоненте emailControl
[formControl]="emailControl"

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.html
> +        [ngClass]="{ 'is-invalid': submitted && email.errors }"
[class.is-invalid]="submitted && email.errors"

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.html
> +        formControlName="password"
formControl

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.html
> +        [ngClass]="{ 'is-invalid': submitted && password.errors }"
[class.is-invalid]

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.html
> +        [disabled]="loading"
для boolean переменных лучше использовать префикс "isLoading"

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.html
> +        routerLink="/{{registerRouterLink}}"
переменная

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.ts
> +  public get email(): AbstractControl { return this.loginForm.controls.email; }
не очень читабельно, лучше переносить тело на новую строку
public get email(): AbstractControl { 
  return this.loginForm.controls.email; 
}

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.ts
> +      email: [undefined, Validators.required],
избегай использование undefined - это штука для самого js
для указания пустоты юзатся null

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/login/login/login.component.ts
> +      .pipe(take(1))
untillComponentDestoyed

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/register/register.component.ts
> +      firstName: ['', Validators.required],
пустота - null

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/core/auth/register/register.component.ts
> +    await this._authService.register(user);
тут у тебя простой объект, а не инстанс класса User

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/shared/models/user.ts
> +    return new User(value.firstName,
для лучшей читабельности стоит перенести на новую строку

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/shared/routes/route-names.ts
> +export function routeNamesObjFactory(): IRouteNames {
имена экспортируемых функций должны быть в uppercase
что-то не так с линтером, если это не подсветило

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/shared/services/logger.services.ts
> +  public error = (err: string): void => {
не стоит использовать стрелочные функции для методов класса

2020-11-23 16:33 UTC, oleg-vasilyev commented on src/app/shared/validators/form-validators.ts
> +export function validateValue(checkControlValue: (value: string) => boolean): ValidatorFn | null {
имя в uppercase

2020-11-24 15:42 UTC, VolhaAdaska commented on src/app/app.component.html
> +          routerLink="/home"
заюзала переменную

2020-11-24 15:42 UTC, VolhaAdaska commented on src/app/app.component.html
> +        [ngIfElse]="loggedOut"
исправила, возможно гит это не сразу покажет) лучше смотреть коммит

2020-11-24 15:43 UTC, VolhaAdaska commented on src/app/app.component.html
> +            routerLink="/register"
заюзала переменную

2020-11-24 15:43 UTC, VolhaAdaska commented on src/app/app.component.html
> +            routerLink="/game"
заюзала переменную

2020-11-24 15:43 UTC, VolhaAdaska commented on src/app/shared/models/user.ts
> +    return new User(value.firstName,
перенесла

2020-11-24 15:43 UTC, VolhaAdaska commented on src/app/shared/routes/route-names.ts
> +export function routeNamesObjFactory(): IRouteNames {
переименовала

2020-11-24 15:43 UTC, VolhaAdaska commented on src/app/shared/services/logger.services.ts
> +  public error = (err: string): void => {
не использую

2020-11-24 15:44 UTC, VolhaAdaska commented on src/app/shared/validators/form-validators.ts
> +export function validateValue(checkControlValue: (value: string) => boolean): ValidatorFn | null {
этот валидатор планировала использовать, но не заюзала, так что вообще удалила, не увидела что коммитаю его

2020-11-24 15:45 UTC, VolhaAdaska commented on src/app/core/auth/register/register.component.ts
> +    await this._authService.register(user);
здесь хочу обсудить с тобой так как я использую инстанс класса User, нужно созвониться, пиши как будет время

2020-11-24 15:45 UTC, VolhaAdaska commented on src/app/app.component.html
> +            routerLink="/login"
заюзала переменную

2020-11-24 15:46 UTC, VolhaAdaska commented on src/app/app.component.html
> +          routerLink="/home"
заюзала переменную

2020-11-24 15:46 UTC, VolhaAdaska commented on src/app/app.component.html
> +            routerLink="/top-users"
заюзала переменную

2020-11-25 08:40 UTC, merged

2020-11-25 09:06 UTC, oleg-vasilyev commented on src/app/app.component.html
> +          routerLink="/{{homeRouterLink}}"
интерполяция только для данных - тут нужен дата байдинг
[routerLink]="homeRouterLink"